# Generated by Django 5.1.7 on 2025-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
