# Generated by Django 5.1.7 on 2025-03-21 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_category_contact_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
